.github/.diff-shellcheck-exceptions.txt
.github/.diff-shellcheck-scripts.txt
.github/workflows/shellcheck_test.yml
Dockerfile
action.yml
src/check-shell.sh
src/functions.sh

differential-shellcheck v1

---

.github/workflows/shellcheck_test.yml
CHANGELOG.md
README.md

Preparation for release of `differential-shellcheck v1`
---
Follow-up to #1 and #2

differential-shellcheck v1 - PART III

---

action.yml

Preparation for release of `differential-shellcheck v1`
---
Follow-up to #1, #2 and #3

differential-shellcheck v1 - PART IV

---

.github/dependabot.yml
.github/release-drafter.yml
.github/workflows/publish-release.yml
.github/workflows/release-drafter.yml
.github/workflows/shellcheck_test.yml
.mergify.yml
README.md

Let's start automating maintanance

---

src/index.sh

It will utilize GitHub Bot for uploading scanning results.

Use `PUT` on `code-scanning/analysis`

---

src/index.sh

This will prevent errors like:
```sh
curl: (22) The requested URL returned error: 403
```
https://github.com/redhat-plumbers/dracut-rhel8/pull/17

Don't upload empty SARIF reports

---

CHANGELOG.md
README.md
src/functions.sh
src/index.sh

- remove unnecessary logs and utilize debug mode
- curl is executed with `--verbose`
- add emojis
- code optimization

Add option to run action in debug mode

---

src/functions.sh

Fix link in Job Summary :fire_extinguisher: 

---

.github/workflows/unit-test.yml
CHANGELOG.md
README.md

Add test coverage :100: 

---

.github/release-drafter.yml

- Add `type: performance` label into `release-drafter.yml`
- Add `collapse-after: 5` to hide dependency updates

Update `release-drafter.yml` :small_airplane: 

---

.github/ISSUE_TEMPLATE/issue-template.yml
.github/advanced-issue-labeler.yml
.github/workflows/issue-labeler.yml
.gitignore

* Support for issue forms
* Enable advanced-issue-labeler

Add support for issue forms :bookmark_tabs: 

---

CHANGELOG.md
README.md
src/functions.sh
src/index.sh

* Also use a more inclusive language.

Fix typos, grammar mistakes and reword some sentences

---

.github/workflows/deploy-production.yml
.github/workflows/differential-shellcheck.yml
src/index.sh

This should allow us to test changes directly in PR. Regression from the time when we started using pre-build containers.
_Happy testing :partying_face:_

Allow to test current changes from PR :hammer_and_wrench: 

---

.github/.differential-shellcheck-scripts.txt
.github/workflows/differential-shellcheck.yml
README.md
action.yml
src/index.sh

Supported severity levels are:
* `error`
* `warning`
* `info`
* `style`

Add support for severity option :bar_chart: 

---

.mergify.yml

This change has been made by @jamacku from https://mergify.com config editor.

ci(Mergify): configuration update :robot: 

---

.mergify.yml

This change has been made by @jamacku from https://mergify.com config editor.

ci(Mergify): Delete head branch after merge :wastebasket: 

---

.mergify.yml

This change has been made by @jamacku from https://mergify.com config editor.

ci(Mergify): Add option to automatically rebase or squash PRs on merge :package: 

---

CHANGELOG.md
src/functions.sh
src/index.sh
test/is_symlink.bats

Don't check symbolic links - avoid warnings :link: 

---

.github/workflows/scorecard-analysis.yml
README.md

Add scorecard GitHub action :duck: :100: 

---

.github/workflows/deploy-test.yml
.github/workflows/unit-test.yml
CHANGELOG.md
Makefile
src/functions.sh
src/index.sh
test/Dockerfile
test/show_versions.bats

Show versions of important packages :exclamation: :package: & Run unit tests with local changes :test_tube:

---

.github/workflows/deploy-test.yml
.github/workflows/differential-shellcheck.yml
.github/workflows/issue-labeler.yml
.github/workflows/publish-release.yml
.github/workflows/release-drafter.yml
.github/workflows/scorecard-analysis.yml

Reverts redhat-plumbers-in-action/differential-shellcheck#147
The permissions are indeed required. Reverting broken patch ...

Revert "Set strict permissions for GitHub Workflows :lock: "

---

.github/workflows/differential-shellcheck.yml
README.md
action.yml
docs/CHANGELOG.md
src/functions.sh
src/index.sh
test/index.bats
test/link_to_results.bats
test/pick_base_and_head_hash.bats

- Limitations: It doesn't work for `force-push`
- #166

Add support for running Action on GitHub `push` event :christmas_tree: 

---

.github/workflows/differential-shellcheck.yml
README.md

Also, adding a section related to usage in private repositories.

Improve permission documentation :book: 

---

test/Dockerfile
test/show_versions.bats

- https://github.com/csutils/csdiff/pull/68
**Full Changelog**: https://github.com/csutils/csdiff/compare/csdiff-2.8.0...csdiff-2.9.0

Update csutils (csdiff) to 2.9.0

---

src/functions.sh

Related to https://github.com/csutils/csmock/pull/101

grep: do not escape `#` and `!` in patterns :green_apple: 

---

.github/workflows/clean-alerts.yml
empty.sarif

This PR will be reverted once Security Alerts are closed

Clean up no longer relevant security alerts

---

Dockerfile
docs/CHANGELOG.md
test/Dockerfile
test/show_versions.bats

**Full Changelog**: https://github.com/csutils/csdiff/compare/csdiff-3.0.2...csdiff-3.0.3

Update `csutils` (`csdiff`) to 3.0.3

---

.github/workflows/unit-test.yml

build(deps): bump codecov/codecov-action from 3.1.4 to 4.3.0

---

Dockerfile
docs/CHANGELOG.md
test/Dockerfile
test/show_versions.bats

https://github.com/csutils/csdiff/releases/tag/csdiff-3.4.0

deps: update csdiff to v3.4.0

---

README.md
src/index.sh

Make available partial results from ShellCheck
new outputs:
- `shellcheck-full`
- `shellcheck-head`
- `shellcheck-base`

feat: improve debugging
