src/index.sh

`--no-index` is required to avoid warnings like:
```
warning: Not a git repository. Use --no-index to compare two paths outside a working tree
```

Use `--no-index` to avoid `git diff` warning

---

src/index.sh

This change will avoid warnings like:
```
fatal: unsafe repository ('/github/workspace' is owned by someone else)
```

Make directory `/github/workspace` git-save

---

src/index.sh

Let's avoid warnings like:
```
fatal: empty string is not a valid pathspec. please use . instead if you meant to match all paths
```

Remove double quotes to avoid git empty pathspec warings

---

src/functions.sh

Check should be: `$# -le 1` since there might be array of length `1`, when only one file was changed.

Fix wrong check in `clean_array()`

---

.github/workflows/shellcheck_test.yml
README.md

Currently ` differential-shellcheck` doesn'ŧ support `push` events.
*Note: Since `github.event.pull_request.base.sha` and `github.event.pull_request.head.sha` aren't available on `push`.*

Action cannot be run on `push`

---

CHANGELOG.md
README.md
src/functions.sh
src/index.sh

Example of Differential ShellCheck job summary:
Changed scripts: `2`
|                             | ❌ Added | ✅ Fixed |
|:---------------------------:|:-------:|:-------:|
| ⚠️ [Errors / Warnings / Notes](https://github.com/redhat-plumbers-in-action/differential-shellcheck/pull/41/files) |  **1**  |  **0**  |
- [Differential ShellCheck Documentation](https://github.com/redhat-plumbers-in-action/differential-shellcheck#readme)
- [ShellCheck Documentation](https://github.com/koalaman/shellcheck#readme)
---
_ℹ️ When you have an issue with GitHub action please try to run it in [debug mode](https://github.blog/changelog/2022-05-24-github-actions-re-run-jobs-with-debug-logging/) and submit an [issue](https://github.com/redhat-plumbers-in-action/differential-shellcheck/issues/new)._

Add support for job summaries :bookmark_tabs: 

---

CHANGELOG.md
README.md
src/functions.sh

Files ending with `.bash` will be automatically verified by differential-shellcheck

Add support for `.bash` extensions :champagne: 

---

CHANGELOG.md
README.md
action.yml

Differential ShellCheck fully supports configuration via `.shellcheckrc`; there is no need for this option anymore.
Please consider using [`.shellcheckrc`](https://github.com/koalaman/shellcheck/blob/master/shellcheck.1.md#rc-files) since `ignored-codes` option may be removed in future major release.

`ignored-codes` option is now deprecated :leaves: 

---

.shellcheckrc
CHANGELOG.md
README.md
action.yml
src/functions.sh
test/clean_array.bats
test/file_to_array.bats
test/has_shebang.bats
test/is_debug.bats
test/is_false.bats
test/is_script_listed.bats
test/is_shell_extension.bats
test/is_true.bats
test/join_by.bats

Adding option to enable sourcing of `external-sources` and enabling it by default as requested in:
- https://github.com/redhat-plumbers/dracut-rhel8/pull/18
- https://github.com/redhat-plumbers-in-action/differential-shellcheck/issues/89

Add option to enable `external-sources` and enable it by default :truck: 

---

README.md

Update made based on a blog post: [Specify theme context for images in Markdown GA](https://github.blog/changelog/2022-08-15-specify-theme-context-for-images-in-markdown-ga/)
Attempting to fix an issue when on the GitHub marketplace are HTML attributes like `#gh-dark-mode-only` and `#gh-light-mode-only` ignored, resulting in displaying both images.

doc: Improve support of GitHub themes :book: 

---

src/functions.sh
test/has_shebang.bats

Follow up to #73 from @jamacku
The original `while` loop will only ever read the first line of the file (which is fine for detecting a shebang), but it's supposed to also account for a `# shellcheck shell=something` directive ([SC1008](https://www.shellcheck.net/wiki/SC1008)), but that directive isn't allowed on the first line.
Additionally;
```shell
#!/bin/mywrapper
echo "Hello World"
```
These changes don't check if the directive is in the right place in the file, just if it exists. The file will be added to the list to be checked, and shellcheck will provide the warning or error about the directive if it's not in the correct place.

Further improve autodetection of shell scripts

---

CHANGELOG.md
README.md
src/functions.sh
test/has_shebang.bats

Supported is:
* `emacs` - `# -*- sh -*-`
* `vi`    - `# vi: (set)? (ft|filetype)=sh`
* `vim`   - `# vim: (set)? (ft|filetype)=sh`
---

Autodetection: add support for `emacs` and `vi/vim` file types specifications

---

Dockerfile

This change gives us the ability to control when to update essential packages.

Pin important packages to their releases :pushpin:  

---

.github/workflows/deploy-test.yml
.github/workflows/differential-shellcheck.yml
.github/workflows/issue-labeler.yml
.github/workflows/publish-release.yml
.github/workflows/release-drafter.yml
.github/workflows/scorecard-analysis.yml

Removed permissions should not be required since this isn't a private repository.

Set strict permissions for GitHub Workflows :lock: 

---

.github/workflows/publish-release.yml
docs/CHANGELOG.md

Don't update `latest` tag, to avoid breakage :stop_sign: 

---

.github/workflows/differential-shellcheck.yml
README.md
action.yml
docs/CHANGELOG.md
src/index.sh

Expose SARIF results as output for further use :package: 

---

README.md

GitHub supports '$default-branch' instead of specifying e.g. 'main' explicitly.
See https://github.blog/changelog/2020-07-22-github-actions-better-support-for-alternative-default-branch-names/ for more info
As requested in https://github.com/redhat-plumbers-in-action/differential-shellcheck/pull/186#discussion_r1072151620

doc: avoid hard-coding main branch name

---

README.md

Reverts redhat-plumbers-in-action/differential-shellcheck#187

Revert "doc: avoid hard-coding main branch name"

---

src/functions.sh

As suggested in: https://github.com/redhat-plumbers-in-action/differential-shellcheck/pull/220#pullrequestreview-1352800750

Utilize DEBUG to run `grep` without `--silent` option :speak_no_evil: 

---

Dockerfile
docs/CHANGELOG.md
test/Dockerfile
test/show_versions.bats

- https://github.com/csutils/csdiff/pull/68
- https://github.com/csutils/csdiff/issues/102
**Full Changelog**: https://github.com/csutils/csdiff/compare/csdiff-2.8.0...csdiff-3.0.0
The new version of csdiff enables us to use [`github/codeql-action/upload-sarif`](https://github.com/github/codeql-action) for uploading scan results to GitHub.

Update csutils (csdiff) to 3.0.0 :diamond_shape_with_a_dot_inside: 

---

README.md
docs/CHANGELOG.md
src/index.sh
src/summary.sh
src/validation.sh
test/evaluate_and_print_defects.bats
test/evaluate_and_print_fixes.bats
test/fixtures/gather_statistics/defects.log
test/fixtures/get_number_of_defects_by_severity/defects.log
test/fixtures/print_statistics/defects.log
test/gather_statistics.bats
test/get_number_of_defects_by_severity.bats
test/print_statistics.bats
test/summary.bats
test/summary_defect_statistics.bats

Let's add statistics about the type and count of new defects.
Example of statistics in console output for `severity: warning`:
Example of statistics in job summary output for `severity: warning`:
---

Add Statistics of defect severities :bar_chart: 

---

.gitignore
README.md
action.yml
docs/CHANGELOG.md
src/functions.sh
test/is_file_inside_scan_directory.bats

Using the new input parameter `scan-directory`, it is now possible to scan only the specified subdirectory of the repository.
The detection of shell scripts will be performed on files inside the scan directory only. It can be combined with the `exclude-path` and `include-path` inputs.
---

Add support for subdirectory scanning :file_folder: 

---

docs/CHANGELOG.md
src/functions.sh

In DEBUG mode, `head` and `grep` was incorrectly called with `''`.
This caused warnings like:
`grep: ^\s*((#|!)|(#\s*!)|(!\s*#))\s*(/usr(/local)?)?/bin/(env\s+)?(sh|ash|bash|dash|ksh|bats)\b: No such file or directory`
In the end, Differential ShellCheck, in some cases, couldn't identify shell scripts correctly in DEBUG mode.

Fix autodetection of shell scripts in DEBUG mode :kiwi_fruit: 

---

README.md

doc: Explain format of path list options

---

.github/workflows/deploy-production.yml
.github/workflows/deploy-release.yml
.github/workflows/deploy-test.yml
.github/workflows/differential-shellcheck.yml
.github/workflows/issue-labeler.yml
.github/workflows/linter.yml
.github/workflows/publish-release.yml
.github/workflows/release-drafter.yml
.github/workflows/scorecard-analysis.yml
.github/workflows/unit-test.yml

Make the version of the used GHA more visible

Make the version of the used GHA more visible :eyes: 

---

src/functions.sh

It doesn't work as expected. Also, the debug output is not very useful.
It fixes the issue when matched strings are outputted into the console:
```
#!/bin/bash
#!/bin/bash
#!/bin/bash
#!/bin/bash
#!/bin/bash
#!/bin/bash
#!/bin/bash
:::::::::::::::::::::
::: Used Versions :::
:::::::::::::::::::::
ShellCheck: 0.9.0
csutils: 3.0.4
:::::::::::::::::::::::::::::::
::: Differential ShellCheck :::
:::::::::::::::::::::::::::::::
📜 List of shell scripts for scanning
ℹ️ No Fixes!
🥳 No defects added. Yay!
✅ SARIF report was successfully uploaded to GitHub
```

Drop support for DEBUG in grep :bug: 

---

README.md

Complements: 1426d7e94f9d ("build(deps): bump actions/upload-artifact from 3.1.3 to 4.0.0")

README.md: bump actions/upload-artifact from v3 to v4

---

src/functions.sh
test/has_shebang.bats

- add support for headers with `mode:` - e.g. `-*- mode: sh -*-`
- add support for headers with `shell script` key

Improve shell script detection based on emacs file mode header :tiger:  

---

src/functions.sh

Should fix #375.
Tested by uploading the payload via curl to an httpd server using `curl -d '<json string>'`, which failed, and by using the payload.json which succeded. Also tested from the docker image.

Fix curl Argument list too long by using a payload.json file

---

src/index.sh
src/summary.sh
src/validation.sh

This is required for #234.
Since pre-commit passes `--user=<UID:GID>` and `--workdir=/src`  - files can not be created at `/`.
Ran the tests:
```
...
summary_useful_links.bats
✓ summary_useful_links()
87 tests, 0 failures
```

Allow specifying WORK_DIR for intermediate files

---

Dockerfile
docs/CHANGELOG.md
test/Dockerfile
test/fixtures/get_defects/defects.log
test/fixtures/get_fixes/fixes.log
test/show_versions.bats

* propagate the imp flag as level in the SARIF format
* propagate endLine/endColumn in the JSON and SARIF formats
Thank you @kdudka and @lzaoral

Update csdiff to `3.2.2` :rocket: 

---

src/index.sh

This is preparation for Fingerprints, which are coming in the next version of csdiff.
- https://github.com/csutils/csdiff/pull/168
> It hashes the data that csdiff uses in its matching algorithm
> and the line content without spaces. For this fingerprint to
> be computed, the results need to include the line content for
> the key event in the format produced by `csgrep --embed-context`.

Embed code context into SARIF output :feet: 

---

Dockerfile
docs/CHANGELOG.md
test/Dockerfile
test/fixtures/generate_SARIF/test.sarif
test/is_github_actions.bats
test/show_versions.bats

* csdiff: match findings by line content without spaces if available
* csgrep --hash-v1: match csdiff/v1 fingerprint prefix
* sarif: initial implementation of csdiff/v1 fingerprints
* sarif: add descriptions for ShellCheck rules
https://github.com/csutils/csdiff/releases/tag/csdiff-3.3.0
Huge Thanks to @kdudka and @lzaoral

Update to csdiff 3.3.0 :feet: 

---

.github/workflows/differential-shellcheck.yml

Run differential-shellcheck on a [`merge_group` GitHub event](https://docs.github.com/en/webhooks/webhook-events-and-payloads?actionType=checks_requested#merge_group), which will be fired when a change is added to the merge queue.
For #433, we want to know what `link_to_results` would be for the code scanning result triggered by a `merge_group` event. We need to try running the workflow on a `merge_group` event (without #433).
An equivalent change works in our private repository.

Run differential ShellCheck on merge_group

---

README.md
action.yml
src/functions.sh
test/is_full_scan_demanded.bats
test/is_strict_check_on_push_demanded.bats
test/pick_base_and_head_hash.bats

Support `merge_group` event natively.
Closes #432
Our team uses [the merge queue](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue) to serialize and validate changes on the default branch. I want to run ShellCheck when a change is added to the merge queue so that I can detect problems introduced by a bad merge before pushing them to the default branch.
While I can configure the workflow to use "manual" triggering event with the base & head SHAs, it'd be convenient if the workflow natively support `merge_group`.
Will see the CI test results.
The definition of `merge_group` event.
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#merge_group

Support `merge_group` event natively

---

.github/workflows/differential-shellcheck.yml
.github/workflows/unit-test.yml
docs/CHANGELOG.md

Use default inputs when running on `merge_group`
Follow-up to:
- https://github.com/redhat-plumbers-in-action/differential-shellcheck/pull/434

Update Differential ShellCheck workflow

---

Dockerfile
test/Dockerfile
test/fixtures/generate_SARIF/test.sarif
test/show_versions.bats

use ShellCheck 0.10.0
use csdiff 3.5.2

Use Fedora 41 as base image & update ShellCheck to 0.10.0

---

src/index.sh

When base branch is out of date (not synced with upstream), the base sha could have value of `0000000000000000000000000000000000000000`. In such case differential ShellCheck can't use it to compare with the head sha and it will exit.
This should make cases like this easier to debug:
```
fatal: Invalid revision range 0000000000000000000000000000000000000000..81375bf5d11901e029aa298f36c8c984ab180adf
```

fix: check if base sha exists

---

src/index.sh

`${WORK_DIR}defects.log` is expected to be formatted from the output of csdiff, it is isn't when simply moved from `${WORK_DIR}full-shellcheck.err`

fix: Make defects log valid for full scan
